apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  destination:
    name: 'in-cluster'
    namespace: external-dns
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    targetRevision: 'v1.15.0'
    chart: external-dns
    helm:
      parameters:
        - name: sources[0]
          value: 'ingress'
        - name: policy
          value: 'sync'
        - name: provider.name
          value: 'cloudflare'
        - name: env[0].name
          value: 'CF_API_TOKEN'
        - name: env[0].valueFrom.secretKeyRef.name
          value: 'cloudflare-api-key'
        - name: env[0].valueFrom.secretKeyRef.key
          value: 'apiKey'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
