apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  project: default
  destination:
    name: 'in-cluster'
    namespace: gitea
  source:
    repoURL: https://dl.gitea.com/charts/
    targetRevision: 'v9.6.1'
    chart: gitea
    helm:
      parameters:
        - name: ingress.enabled
          value: 'true'
        - name: ingress.tls[0].secretName
          value: 'taiga-oakdew-cert'
        - name: ingress.annotations.external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: 'true'
        - name: ingress.annotations.external-dns.alpha.kubernetes.io/hostname
          value: 'gitea.oakdew.biz'
        - name: ingress.annotations.external-dns.alpha.kubernetes.io/target
          value: '5860ec34-d45a-45b8-b1e4-9fefd97a59a4.cfargotunnel.com'
        - name: ingress.hosts[0].host
          value: gitea.oakdew.biz
        - name: ingress.hosts[0].paths[0].path
          value: '/'
        - name: ingress.hosts[0].paths[0].pathType
          value: 'Prefix'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
