apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: taiga-oakdew-cert
  namespace: taiga
spec:
  secretName: taiga-oakdew-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - taiga.oakdew.biz
