apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
  namespace: cloudflare
type: Opaque
data:
  TUNNEL_TOKEN: ZXlKaElqb2lNVE14TVdSbU5qWTBaVEZtTVdRd05tSTNZamM1WmpFek9EQmhNVGt3WlRRaUxDSjBJam9pTlRnMk1HVmpNelF0WkRRMVlTMDBOV0k0TFdJeFpUUXRPV1psWm1RNU4yRTFPV0UwSWl3aWN5STZJbHBxVlhsTmFtc3pXbGRWZEU5VVFYcE5lVEF3VGxSWmVreFhSVFZaZWxGMFdtcG9iRnBxVm1oYWJWa3lUWHByZWlKOQ==
